# GENERATED by scripts/run_calibration.py -- DO NOT EDIT
"""Calibrated scientific defaults frozen from calibration partition."""
from __future__ import annotations

from hydroseason._boundary_recoverability import RecoverabilityThresholds
from hydroseason._cycle_phase import PhaseThresholds
from hydroseason._evidence import EvidenceThresholds

CALIBRATION_VERSION = "0.2.0-audit.1"
CALIBRATION_FINGERPRINT = "8d32bc8cd7b4757b129eedb082d30c029dcbe59c66957f3c86d1ba96aa4ee3db"

EVIDENCE_AUTHORITY_SCOPE = "experimental_challenger"
RECOVERABILITY_AUTHORITY_SCOPE = "experimental_challenger"
PHASE_AUTHORITY_SCOPE = "authoritative_for_four_phase_labels_only"

EVIDENCE_DEFAULTS = EvidenceThresholds(
    seasonal_cv_skill=0.8,
    periodicity_alpha=0.1,
    amplitude_noise_ratio=2.0,
    mode_min_frequency=0.5,
    mode_min_separation_months=2,
    strong_timing_concentration=0.8,
    weak_timing_concentration=0.5,
    min_timing_years=10,
)

RECOVERABILITY_DEFAULTS = RecoverabilityThresholds(
    min_years=5,
    min_coverage=0.8,
    min_within_1_month=0.8,
    within_1_month_wilson_floor=0.3,
    max_p90_error_months=2.0,
    admit_insufficient_drift=True,
)

PHASE_DEFAULTS = PhaseThresholds(
    phase_low_fraction=0.25,
    phase_high_fraction=0.8,
    phase_min_duration_months=1,
    phase_smoothing_window=3,
)
