# GENERATED by scripts/run_calibration.py -- DO NOT EDIT
"""Calibrated scientific defaults frozen from calibration partitions."""
from __future__ import annotations

from hydroseason._calibration import EvidenceThresholds, RecoverabilityThresholds
from hydroseason._timing_identifiability import TimingIdentifiabilityThresholds

CALIBRATION_VERSION = '0.2.0-audit.2'
CALIBRATION_FINGERPRINT = 'd98a4e55bb549836a3b3d1e6896362342b99583eed61e928926c40b4957bebb2'
CALIBRATION_ENVIRONMENT = {'python': '3.12.13', 'numpy': '2.4.6', 'pandas': '3.0.3'}

EVIDENCE_AUTHORITY_SCOPE = 'experimental_challenger'
RECOVERABILITY_AUTHORITY_SCOPE = 'experimental_challenger'

EVIDENCE_DEFAULTS = EvidenceThresholds(**{'seasonal_cv_skill': 0.3, 'periodicity_alpha': 0.025, 'amplitude_noise_ratio': 2.0, 'mode_min_frequency': 0.5, 'mode_min_separation_months': 2, 'strong_timing_concentration': 0.8, 'weak_timing_concentration': 0.5, 'min_timing_years': 5})
RECOVERABILITY_DEFAULTS = RecoverabilityThresholds(**{'min_years': 5, 'min_coverage': 0.8, 'min_within_1_month': 0.8, 'within_1_month_wilson_floor': 0.3, 'max_p90_error_months': 2.0, 'admit_insufficient_drift': True})

TIMING_IDENTIFIABILITY_AUTHORITY_SCOPE = 'candidate_for_established_0_2_0'
TIMING_IDENTIFIABILITY_FINGERPRINT = 'e6cdf3ce960aa011711dc90e3ef4fb0135513eadaf471f4ac9e0656f80884735'
TIMING_IDENTIFIABILITY_DEFAULTS = TimingIdentifiabilityThresholds(**{'min_amplitude_to_floor_ratio': 3.0, 'min_peak_water_pixels': 5, 'max_point_span_months': 0, 'max_boundary_interval_months': 2, 'min_informative_years': 7})

# BEGIN RECURRENCE IDENTIFIABILITY DEFAULTS
from hydroseason._recurrence_identifiability import RecurrencePolicy

RECURRENCE_AUTHORITY_SCOPE = 'candidate_for_established_0_2_0'
RECURRENCE_FINGERPRINT = '4b08cd352ce67a6be999e28734963b0ce6b989163923a21d76da8762c5314b00'
RECURRENCE_POLICY: RecurrencePolicy = 'annual_shape_match'
# END RECURRENCE IDENTIFIABILITY DEFAULTS
