# GENERATED by scripts/run_calibration.py --trough-refinement -- DO NOT EDIT
"""Frozen Pass-2 candidate; not established without the blinded real-cohort gate."""
from hydroseason._trough_refinement import TroughRefinementPolicy

TROUGH_REFINEMENT_AUTHORITY_SCOPE = 'trough_refinement_candidate_0_1'
TROUGH_REFINEMENT_FINGERPRINT = '049f16f04035d6d1dadf805192bce57b7c0750cab283c9410881d9302cb9ea2d'
TROUGH_REFINEMENT_POLICY = TroughRefinementPolicy(
    huber_k=1.345,
    profile_loss_cutoff=0.05,
    pulse_z=1.5,
    version='trough_refinement_candidate_0_1',
)
