"""Frozen direct_profile_combined candidate policy.

Unlike ``_trough_refinement_defaults.py`` (auto-generated by
``scripts/run_calibration.py --trough-refinement``), there is no grid-search
calibration pipeline for this candidate yet -- ``_trough_refinement_calibration.py``
only tunes ``shape_fit``'s hyperparameter family (see its
``TROUGH_REFINEMENT_AUTHORITY_SCOPE``). The shape hyperparameters are carried
over directly from Stage B development/validation
(``case_studies/results/low-state-direct-profile-v2/findings.md``: dev-matrix
coverage 98.6%, reserved-seed coverage 97.75%) and an informal single-reviewer
real-catchment spot check (17 disagreement cycles across 5 development
catchments plus Kakadu National Park; candidate preferred or honestly-
uncertain-in-the-right-place in 13/17 -- see
``docs/migrations/trough-refinement-candidate.md``).

**Those Stage B coverage figures do not speak to ``delta_rel``.** That corpus
places every family's low state at exactly the same level (12.0 percentage
points after scaling) and ran a fixed 0.4 pp absolute margin against it --
an effective 3.33% of the low-state level, close to the 5% shipped here. A
single-scale corpus cannot distinguish an absolute margin from a proportional
one, which is precisely why the defect this parameter fixes surfaced only on
real records whose trough level varies between cycles. The figures are
therefore neither invalidated nor confirmatory for this choice; the evidence
for it is the real-catchment review below.

``delta_rel=0.05`` -- a month within 5% of the low-state level counts as
still in the low state -- is bracketed by the reviewed record itself, on two
independent sides. Reviewing every cycle of Fitzroy River and Gilbert River
(42 in total) split them cleanly with nothing in between: the boundaries the
reviewer accepted were all exactly the cycle's own trough (a 0.0% rise),
while every boundary the reviewer rejected sat 10.4% to 56.8% above it. On
the equivalent side, Gilbert River HY2006's genuinely flat October-December
plateau spans +4.4% and must stay tied. 0.05 sits just above that
equivalent-side edge, so it honours "a few percent is noise" without being
tuned to the 10.4% it must exclude -- the same construction, and the same
value, as ``_boundary.py``'s ``_RAW_MINIMUM_REL_TOLERANCE``.

Being proportional is what makes a single default defensible at all: the
retired absolute margin could not serve even one catchment's own cycles,
since Fitzroy's trough level ranges 0.0249 to 0.0521 percentage points
across its own record. A catchment whose low state is genuinely a different
*shape* -- not merely a different scale -- still warrants its own value.

Not established: default-policy promotion still requires the blinded
real-cohort gate (unrun for this target -- the existing
``trough-refinement-span-cohort-v1`` labels were frozen for the ``shape_fit``
target and are not reusable here without a fresh blinded round).
"""
from hydroseason._trough_refinement import TroughRefinementPolicy

TROUGH_REFINEMENT_DIRECT_PROFILE_AUTHORITY_SCOPE = "direct_profile_combined_v1"
TROUGH_REFINEMENT_DIRECT_PROFILE_POLICY = TroughRefinementPolicy(
    huber_k=1.345,
    profile_loss_cutoff=0.05,
    pulse_z=1.5,
    version="direct_profile_combined_v1",
    candidate="direct_profile_combined",
    delta_rel=0.05,
    l_uncertainty_k=2.0,
    scale_mode="combined",
)
