# GENERATED by scripts/run_calibration.py --trough-refinement -- DO NOT EDIT
"""Frozen Pass-2 candidate; not established without the blinded real-cohort gate."""
from hydroseason._trough_refinement import TroughRefinementPolicy

TROUGH_REFINEMENT_AUTHORITY_SCOPE = 'trough_refinement_candidate_0_2'
TROUGH_REFINEMENT_FINGERPRINT = '850122592d37124a5800052a5397cd514f127fe398c176020273023866a0fbb0'
TROUGH_REFINEMENT_POLICY = TroughRefinementPolicy(
    huber_k=1.345,
    profile_loss_cutoff=0.05,
    pulse_z=1.5,
    version='trough_refinement_candidate_0_2',
)
