"""Frozen direct_profile_combined candidate policy.

Unlike ``_trough_refinement_defaults.py`` (auto-generated by
``scripts/run_calibration.py --trough-refinement``), there is no grid-search
calibration pipeline for this candidate yet -- ``_trough_refinement_calibration.py``
only tunes ``shape_fit``'s hyperparameter family (see its
``TROUGH_REFINEMENT_AUTHORITY_SCOPE``). These values are carried over directly
from Stage B development/validation
(``case_studies/results/low-state-direct-profile-v2/findings.md``: dev-matrix
coverage 98.6%, reserved-seed coverage 97.75%) and an informal single-reviewer
real-catchment spot check (17 disagreement cycles across 5 development
catchments plus Kakadu National Park; candidate preferred or honestly-
uncertain-in-the-right-place in 13/17 -- see
``docs/migrations/trough-refinement-candidate.md``).

``delta_pp=0.02`` is an ENGINEERING default, not a scientific measurement-error
estimate: it was validated only against catchments whose low-state extent
region sits in the roughly 0.01-2% range. A catchment with a materially
different trough-region scale should supply its own ``delta_pp`` rather than
rely on this default -- see ``TroughRefinementPolicy.delta_pp``'s docstring.

Not established: default-policy promotion still requires the blinded
real-cohort gate (unrun for this target -- the existing
``trough-refinement-span-cohort-v1`` labels were frozen for the ``shape_fit``
target and are not reusable here without a fresh blinded round).
"""
from hydroseason._trough_refinement import TroughRefinementPolicy

TROUGH_REFINEMENT_DIRECT_PROFILE_AUTHORITY_SCOPE = "direct_profile_combined_v1"
TROUGH_REFINEMENT_DIRECT_PROFILE_POLICY = TroughRefinementPolicy(
    huber_k=1.345,
    profile_loss_cutoff=0.05,
    pulse_z=1.5,
    version="direct_profile_combined_v1",
    candidate="direct_profile_combined",
    delta_pp=0.02,
    l_uncertainty_k=2.0,
    scale_mode="combined",
)
