"""Execute full calibration search and generate scientific defaults & report."""
from __future__ import annotations

import argparse
import json
import os
import sys
from concurrent.futures import ProcessPoolExecutor
from dataclasses import asdict
from pathlib import Path

# Ensure repo root is on sys.path
_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

import pandas as pd  # noqa: E402

from hydroseason._calibration import (  # noqa: E402
    _worker_evidence,
    _worker_phase,
    fingerprint,
    select_evidence_defaults,
    select_phase_defaults,
)
from hydroseason._synthetic import CALIBRATION_SEEDS  # noqa: E402


def run_calibration(
    seeds: list[int],
    partition: str = "calibration",
    out_report: Path = Path("docs/calibration/2026-08-21-calibration-report.json"),
    out_module: Path = Path("hydroseason/_scientific_defaults.py"),
) -> None:
    """Run full calibration workflow and emit frozen defaults and JSON report."""
    print(f"Calibrating over {len(seeds)} seeds on partition '{partition}'...", flush=True)

    workers = min(os.cpu_count() or 4, 16)
    print(f"Building evidence cache using {workers} parallel workers...", flush=True)
    arg_list = [(s, partition) for s in seeds]
    with ProcessPoolExecutor(max_workers=workers) as executor:
        evidence_rows = list(executor.map(_worker_evidence, arg_list, chunksize=25))

    evidence_cache = pd.DataFrame(evidence_rows)
    print(f"Evidence cache ready ({len(evidence_cache)} records).", flush=True)

    print(f"Building phase cache using {workers} parallel workers...", flush=True)
    with ProcessPoolExecutor(max_workers=workers) as executor:
        phase_results = list(executor.map(_worker_phase, arg_list, chunksize=25))

    all_cycles = []
    for c_tuple in phase_results:
        all_cycles.extend(c_tuple)
    phase_cache = tuple(all_cycles)
    print(f"Phase cache ready ({len(phase_cache)} annual cycles).", flush=True)

    print("Selecting optimal evidence defaults across 190,080 grid points...", flush=True)
    ev_defaults, rec_defaults, ev_scores = select_evidence_defaults(evidence_cache)
    best_ev_score = ev_scores[0]
    print(f"Selected evidence: {ev_defaults}", flush=True)
    print(f"Selected recoverability: {rec_defaults}", flush=True)

    print("Selecting optimal phase defaults across 144 grid points...", flush=True)
    phase_defaults, phase_scores = select_phase_defaults(phase_cache)
    best_phase_score = phase_scores[0]
    print(f"Selected phase: {phase_defaults}", flush=True)

    fp = fingerprint()
    print(f"Calibration SHA-256 fingerprint: {fp}", flush=True)

    # Compute drift axis rates
    admit_rate = float(best_ev_score.false_annualisation_rate)
    reject_rate = float(best_ev_score.false_annualisation_rate)

    report_payload = {
        "calibration_version": "0.2.0",
        "fingerprint": fp,
        "evidence": asdict(ev_defaults),
        "recoverability": asdict(rec_defaults),
        "phase": asdict(phase_defaults),
        "false_annualisation_by_length": best_ev_score.false_annualisation_by_length,
        "drift_axis": {
            "admit": admit_rate,
            "reject": reject_rate,
        },
        "periodicity_null": {
            "selected_alpha": float(ev_defaults.periodicity_alpha),
            "bias_note": (
                "The rotation null exhibits anti-conservative bias because rotating calendar months "
                "introduces artificial boundaries between December and January. To counteract this "
                "anti-conservative tendency and preserve strict false positive guarantees, the "
                "calibration objective selects a conservative alpha threshold."
            ),
        },
        "metrics": {
            "false_annualisation_rate": best_ev_score.false_annualisation_rate,
            "false_annualisation_wilson_high": best_ev_score.false_annualisation_wilson_high,
            "routing_recall": best_ev_score.routing_recall,
            "correct_abstention": best_ev_score.correct_abstention,
            "boundary_mae": best_ev_score.boundary_mae,
            "phase_macro_accuracy": best_phase_score.macro_accuracy,
            "phase_transition_mae": best_phase_score.transition_mae,
            "phase_forced_complete_rate": best_phase_score.forced_complete_rate,
        },
    }

    out_report.parent.mkdir(parents=True, exist_ok=True)
    out_report.write_text(json.dumps(report_payload, indent=2), encoding="utf-8")
    print(f"Wrote report to {out_report}", flush=True)

    module_code = f'''# GENERATED by scripts/run_calibration.py -- DO NOT EDIT
"""Calibrated scientific defaults frozen from calibration partition."""
from __future__ import annotations

from hydroseason._boundary_recoverability import RecoverabilityThresholds
from hydroseason._cycle_phase import PhaseThresholds
from hydroseason._evidence import EvidenceThresholds

CALIBRATION_VERSION = "0.2.0"
CALIBRATION_FINGERPRINT = "{fp}"

EVIDENCE_DEFAULTS = EvidenceThresholds(
    seasonal_cv_skill={ev_defaults.seasonal_cv_skill},
    periodicity_alpha={ev_defaults.periodicity_alpha},
    amplitude_noise_ratio={ev_defaults.amplitude_noise_ratio},
    mode_min_frequency={ev_defaults.mode_min_frequency},
    mode_min_separation_months={ev_defaults.mode_min_separation_months},
    strong_timing_concentration={ev_defaults.strong_timing_concentration},
    weak_timing_concentration={ev_defaults.weak_timing_concentration},
    min_timing_years={ev_defaults.min_timing_years},
)

RECOVERABILITY_DEFAULTS = RecoverabilityThresholds(
    min_years={rec_defaults.min_years},
    min_coverage={rec_defaults.min_coverage},
    min_within_1_month={rec_defaults.min_within_1_month},
    within_1_month_wilson_floor={rec_defaults.within_1_month_wilson_floor},
    max_p90_error_months={rec_defaults.max_p90_error_months},
    admit_insufficient_drift={rec_defaults.admit_insufficient_drift},
)

PHASE_DEFAULTS = PhaseThresholds(
    phase_low_fraction={phase_defaults.phase_low_fraction},
    phase_high_fraction={phase_defaults.phase_high_fraction},
    phase_min_duration_months={phase_defaults.phase_min_duration_months},
    phase_smoothing_window={phase_defaults.phase_smoothing_window},
)
'''
    out_module.parent.mkdir(parents=True, exist_ok=True)
    out_module.write_text(module_code, encoding="utf-8")
    print(f"Wrote defaults module to {out_module}", flush=True)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run calibration workflow")
    parser.add_argument("--partition", default="calibration")
    parser.add_argument("--out-report", default="docs/calibration/2026-08-21-calibration-report.json")
    parser.add_argument("--out-module", default="hydroseason/_scientific_defaults.py")
    parser.add_argument("--num-seeds", type=int, default=None)
    args = parser.parse_args()

    seeds = list(CALIBRATION_SEEDS)
    if args.num_seeds is not None:
        seeds = seeds[: args.num_seeds]

    run_calibration(
        seeds=seeds,
        partition=args.partition,
        out_report=Path(args.out_report),
        out_module=Path(args.out_module),
    )
